name: Bug report
description: File a bug/issue
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the issue.
    validations:
      required: true
  - type: input
    attributes:
      label: Home Assistant version
  - type: input
    attributes:
      label: Mobile app (if used) and device
  - type: textarea
    attributes:
      label: Logs / screenshots
